### ISSUE TITLE
Improve integration tests via github action services

### ISSUE THREAD

**Issue by Xuanwo** [tikv/client-go#135]
Maybe we can improve the integration test via github action services as described in https://docs.github.com/en/actions/guides/about-service-containers

```yaml
# Service containers to run with `runner-job`
services:
  # Label used to access the service container
  redis:
    # Docker Hub image
    image: redis
    #
    ports:
      # Opens tcp port 6379 on the host and service container
      - 6379:6379
```
