### ISSUE TITLE
Stale-Read load is unbalanced

### ISSUE THREAD

**Issue by crazycs520** [tikv/client-go#857]
## TiDB Cluster Topology

```yaml
tidb_servers:
  - host: 192.168.78.2
      labels: { zone: "z1", host: "tidb0" }
tikv_servers:
  - host: 192.168.80.2
    config:
      server.labels: { zone: "z1", host: "tikv0" }
  - host: 192.168.80.3
    config:
      server.labels: { zone: "z1", host: "tikv1" }
  - host: 192.168.80.4
    config:
      server.labels: { zone: "z2", host: "tikv2" }
```

Then send stale-read point-select SQL request to `tidb0`, then the stale-read request in TiKV should be balanced in `tikv0` and `tikv1`, and doesn't have stale-read request in `tikv2`. But in TiDB v6.5.3, the stale-read request in TiKV is unbalanced. Following is the TiKV metrics:

<img width="1445" alt="image" src="https://github.com/tikv/client-go/assets/26020263/a0ac0a30-a96e-490e-8933-ec9e94266224">

As you can see, the stale-read get request 

The stale-read get request on tikv0 is twice as high as on tikv1, which is not as expected, and there is no stale-read get request on tikv2, which is expected.
